# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
    - master

language: R
cache: packages
warnings_are_errors: false

r_binary_packages:
  - devtools
  - roxygen2

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::codecov()'

after_failure:
  - Rscript -e 'devtools::test()'
